#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : moonjit
Version  : 2.2.0
Release  : 15
URL      : file:///insilications/build/clearlinux/packages/moonjit/moonjit-2.2.0.tar.gz
Source0  : file:///insilications/build/clearlinux/packages/moonjit/moonjit-2.2.0.tar.gz
Summary  : Just-in-time compiler for Lua
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1 MPL-1.1
Requires: moonjit-bin = %{version}-%{release}
Requires: moonjit-data = %{version}-%{release}
Requires: moonjit-lib = %{version}-%{release}
Requires: moonjit-man = %{version}-%{release}
BuildRequires : findutils
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: build.patch

%description
The files in this directory are only used during the build process of LuaJIT.
For cross-compilation, they must be executed on the host, not on the target.

%package bin
Summary: bin components for the moonjit package.
Group: Binaries
Requires: moonjit-data = %{version}-%{release}

%description bin
bin components for the moonjit package.


%package data
Summary: data components for the moonjit package.
Group: Data

%description data
data components for the moonjit package.


%package dev
Summary: dev components for the moonjit package.
Group: Development
Requires: moonjit-lib = %{version}-%{release}
Requires: moonjit-bin = %{version}-%{release}
Requires: moonjit-data = %{version}-%{release}
Provides: moonjit-devel = %{version}-%{release}
Requires: moonjit = %{version}-%{release}

%description dev
dev components for the moonjit package.


%package lib
Summary: lib components for the moonjit package.
Group: Libraries
Requires: moonjit-data = %{version}-%{release}

%description lib
lib components for the moonjit package.


%package man
Summary: man components for the moonjit package.
Group: Default

%description man
man components for the moonjit package.


%package staticdev
Summary: staticdev components for the moonjit package.
Group: Default
Requires: moonjit-dev = %{version}-%{release}

%description staticdev
staticdev components for the moonjit package.


%prep
%setup -q -n moonjit
cd %{_builddir}/moonjit
%patch1 -p1

%build
unset http_proxy
unset https_proxy
unset no_proxy
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1599406306
export GCC_IGNORE_WERROR=1
## altflags_pgo content
## pgo generate
export PGO_GEN="-fprofile-generate=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-update=atomic -fprofile-arcs -ftest-coverage --coverage -fprofile-partial-training"
export CFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -fipa-pta -ffat-lto-objects -fPIC $PGO_GEN"
export FCFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -fipa-pta -ffat-lto-objects -fPIC $PGO_GEN"
export FFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -fipa-pta -ffat-lto-objects -fPIC $PGO_GEN"
export CXXFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -fvisibility-inlines-hidden -pipe -fipa-pta -ffat-lto-objects -fPIC $PGO_GEN"
export LDFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -fipa-pta -fPIC $PGO_GEN"
## pgo use
## -ffat-lto-objects -fno-PIE -fno-PIE -m64 -no-pie -fpic -fvisibility=hidden -flto-partition=none
## gcc: -feliminate-unused-debug-types -fipa-pta -flto=16 -Wno-error -Wp,-D_REENTRANT -fno-common
export PGO_USE="-fprofile-use=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-correction -fprofile-partial-training"
export CFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC $PGO_USE"
export FCFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC $PGO_USE"
export FFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC $PGO_USE"
export CXXFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC $PGO_USE"
export LDFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC $PGO_USE"
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
# export PATH="/usr/lib64/ccache/bin:$PATH"
# export CCACHE_NOHASHDIR=1
# export CCACHE_DIRECT=1
# export CCACHE_SLOPPINESS=pch_defines,locale,time_macros
# export CCACHE_DISABLE=1
## altflags_pgo end
##
%define _lto_cflags 1
##
export CFLAGS="${CFLAGS_GENERATE}"
export CXXFLAGS="${CXXFLAGS_GENERATE}"
export FFLAGS="${FFLAGS_GENERATE}"
export FCFLAGS="${FCFLAGS_GENERATE}"
export LDFLAGS="${LDFLAGS_GENERATE}"
make  %{?_smp_mflags}  amalg MULTILIB=lib64

make check || :
make CFLAGS="${CFLAGS_GENERATE}" LDFLAGS="${LDFLAGS_GENERATE}" BENCH_DURATION=4 bench || :
make clean
export CFLAGS="${CFLAGS_USE}"
export CXXFLAGS="${CXXFLAGS_USE}"
export FFLAGS="${FFLAGS_USE}"
export FCFLAGS="${FCFLAGS_USE}"
export LDFLAGS="${LDFLAGS_USE}"
make  %{?_smp_mflags}  amalg MULTILIB=lib64


%check
export LANG=C.UTF-8
unset http_proxy
unset https_proxy
unset no_proxy
make check || :

%install
export SOURCE_DATE_EPOCH=1599406306
rm -rf %{buildroot}
%make_install MULTILIB=lib64
## install_append content
# ln -sf luajit-2.1.0-beta3 %{buildroot}/usr/bin/luajit
# cp src/*.h %{buildroot}/usr/include/moonjit-2.2/
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/luajit
/usr/bin/moonjit-2.3.0-dev

%files data
%defattr(-,root,root,-)
/usr/share/moonjit-2.3.0-dev/jit/bc.lua
/usr/share/moonjit-2.3.0-dev/jit/bcsave.lua
/usr/share/moonjit-2.3.0-dev/jit/dis_arm.lua
/usr/share/moonjit-2.3.0-dev/jit/dis_arm64.lua
/usr/share/moonjit-2.3.0-dev/jit/dis_arm64be.lua
/usr/share/moonjit-2.3.0-dev/jit/dis_mips.lua
/usr/share/moonjit-2.3.0-dev/jit/dis_mips64.lua
/usr/share/moonjit-2.3.0-dev/jit/dis_mips64el.lua
/usr/share/moonjit-2.3.0-dev/jit/dis_mipsel.lua
/usr/share/moonjit-2.3.0-dev/jit/dis_ppc.lua
/usr/share/moonjit-2.3.0-dev/jit/dis_x64.lua
/usr/share/moonjit-2.3.0-dev/jit/dis_x86.lua
/usr/share/moonjit-2.3.0-dev/jit/dump.lua
/usr/share/moonjit-2.3.0-dev/jit/p.lua
/usr/share/moonjit-2.3.0-dev/jit/v.lua
/usr/share/moonjit-2.3.0-dev/jit/vmdef.lua
/usr/share/moonjit-2.3.0-dev/jit/zone.lua

%files dev
%defattr(-,root,root,-)
/usr/include/moonjit-2.3/lauxlib.h
/usr/include/moonjit-2.3/lua.h
/usr/include/moonjit-2.3/lua.hpp
/usr/include/moonjit-2.3/luaconf.h
/usr/include/moonjit-2.3/luajit.h
/usr/include/moonjit-2.3/lualib.h
/usr/lib64/libluajit-5.1.so
/usr/lib64/pkgconfig/luajit.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libluajit-5.1.so.2
/usr/lib64/libluajit-5.1.so.2.3.0

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/luajit.1

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libluajit-5.1.a
